### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/freshbitsweb/laratables/pull/111/commits/798453101590664d3f6bd6e8d3be35d742230644?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laratables.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "freshbitsweb/laratables": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by SanderMuller** [comment]
@gauravmak installed this in my project, runs without issues. Think I am using most features (controlling query, custom columns, searching, ordering, etc)

**Comment by gauravmak** [comment]
Thanks for the heads up @SanderMuller 

I will do the needful by the weekend.

**Pull request merged**
