### PR TITLE
Fixes to override in custom class

### LINKED ISSUE #42: laratablesRowClass in custom table class
Hi, I've created a custom class to store the Laratables logic, so my model is cleaner.

When I try to add the laratablesRowClass function to my custom class to add custom CSS class names to table rows, I receive an error that CompletedAudit->laratablesRowClass is undefined.  

If I then _also_ add a laratablesRowClass function to the model, and put my logic in there, the class names are added.

If I then _remove_ the laratablesRowClass from my custom Laratables class, but leave it in the model, it stops working as if it isn't even there.

Is this intended behaviour, or should I be able to put a function called laratablesRowClass in my custom Laratables class and it is all picked up from there?

Controller method:
~~~
   public function completed_audits_datatables() {
      return Laratables::recordsOf(CompletedAudit::class,CompletedAuditsTable::class);
    }
~~~

Laratables class:
~~~
<?php
  namespace App\Laratables;

  use App\CompletedAudit;

  class CompletedAuditsTable 
  {
    ...

    /**
     * Bug in laratables? - needed as stub here and function in model to be picked up.
     */
    public function laratablesRowClass() { }
  }
~~~

Model:
~~~
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;

class CompletedAudit extends Model implements Auditable
{
    ...

    public function laratablesRowClass() {
      $class = $this->type->colour ? $this->type->colour.' lighten-4' : null;
      return $class;
    }
}
~~~

### PR DESCRIPTION
**Pull request by CJau**
- laratablesRowClass and laratablesRowData more consistent with other override functions
 - updated README to describe new behaviour

Fixes #42

### CODE REVIEW

**Comment by gauravmak** [comment]
Thanks @CJau777 

We would also need updated tests before this can be merged.

**Comment by CJau** [comment]
OK. I'll have a look as time allows and update the PR.

**Comment by CJau** [comment]
Relevant tests have been updated and all checks are now passing.  Not sure if any new tests are needed? The existing set is reasonably comprehensive as far as this change is concerned.

Also, given that the methods are changing to static, this is presumably a breaking change for anyone that has used the previous way.  This way is more consistent with other methods that customise Laratables though.

**Comment by gauravmak** [comment]
@CJau777 Thanks. You're right there. Will need to plan out the release accordingly.

**Comment by CJau** [comment]
@gauravmak is there anything else you need from me for this PR other than to plan/release when it fits with your schedule?

**Comment by gauravmak** [comment]
@CJau777 Nothing for now. I will update here if there is anything, thanks.

**Comment by gauravmak** [comment]
Just saw that your code was perfect CJau777. There were a few more things to be added which I did and release v2.0.0. thanks for the help.

**Pull request closed without merging**
