### PR TITLE
Implemented hard length limit feature.

### PR DESCRIPTION
**Pull request by latheesan-k**
This new configuration allows you to implement a server side hard limit of length to restrict the maximum number of rows to show.

Now user's can't modify the 'Show' dropdown and change the `value` (using something like inspect element of chrome) to something silly like `1000000`  and try to get the server to return more rows.

### CODE REVIEW

**Comment by gauravmak** [comment]
Thanks @latheesan-k 

I appreciate your contribution.

Maybe we can just keep 100 the maximum limit and avoid an extra config variable. As most people would be happy with 100 and default datatables dropdown is also up to 100 only.

And we can put the code like:

```
->limit(min((int) request('length'), 100))
```

Can you please update accordingly.

**Comment by latheesan-k** [comment]
Sure, I'll update the PR.

**Comment by latheesan-k** [comment]
@gauravmak PR updated.

**Comment by gauravmak** [comment]
@latheesan-k Thanks :)

**Pull request merged**
